### ISSUE TITLE
Exercise-3 "botocore.exceptions.NoCredentialsError: Unable to locate credentials"

### ISSUE THREAD

**Issue by floren007** [danielbeach/data-engineering-practice#18]
When I try  to print a list of files that have bucket s3, console says to me "botocore.exceptions.NoCredentialsError: Unable to locate credentials"

i write my code:

import boto3

def main():
    s3= boto3.client('s3')
    paquete=s3.download_file('commoncrawl','crawl-data/CC-MAIN-2022-05/wet.paths.gz','wet.paths.gz')
    paquete.content
   

if __name__ == "__main__":
    main()

**Comment by InosRahul** [comment]
https://commoncrawl.org/tag/s3/. Read the 2nd point. I think you have to authenticate with amazon s3 to access the data with boto3. 
Alternatively you can use https://data.commoncrawl.org/  to access the data

**Comment by floren007** [comment]
I mean i have no account on aws. So i cant authenticate
________________________________
De: Rahul Soni ***@***.***>
Enviado: domingo, 4 de junio de 2023 7:57
Para: danielbeach/data-engineering-practice ***@***.***>
Cc: Florentino ***@***.***>; Author ***@***.***>
Asunto: Re: [danielbeach/data-engineering-practice] Exercise-3 "botocore.exceptions.NoCredentialsError: Unable to locate credentials" (Issue #18)


https://commoncrawl.org/tag/s3/. Read the 2nd point. I think you have to authenticate with amazon s3 to access the data with boto3.
Alternatively you can use https://data.commoncrawl.org/ to access the data

**Comment by InosRahul** [comment]
> I mean i have no account on aws. So i cant authenticate

Even I didn't have account on aws, so I didn't use the boto3 library. I got the data from this url https://data.commoncrawl.org/

**Comment by mp-v2** [comment]
Adding instructions here for the AWS credentials, also for future me.

This is the most useful guide:
https://boto3.amazonaws.com/v1/documentation/api/1.18.54/guide/credentials.html

To use boto3 with AWS, you need to provide AWS credentials. Whether or not the bucket itself is public.

> Boto3 credentials can be configured in multiple ways. Regardless of the source or sources that you choose, you must have both AWS credentials and an AWS Region set in order to make requests.

source: https://boto3.amazonaws.com/v1/documentation/api/1.18.54/guide/credentials.html

Note, other methods of accessing AWS do not need AWS credentials for public buckets:

> For example, if you want to download a protected file from an Amazon Simple Storage Service (Amazon S3) bucket, your credentials must allow that access. If your credentials don't show you are authorized to download the file, AWS denies your request. However, your AWS security credentials aren't required for you to download a file in an Amazon S3 bucket that is publicly shared.

source: https://docs.aws.amazon.com/IAM/latest/UserGuide/security-creds.html

Therefore, to make credentials:
- Make an AWS account
- Open the [AWS Console](https://console.aws.amazon.com/)
- Click on your username near the top right and select Security Credentials
- Click on Users in the sidebar
- Click on your username
- Click on the Security Credentials tab
- Click Create Access Key (***)
- Click Show User Security Credentials

***="Root user access keys are not recommended", instead use an IAM role:
- IAM -> Roles -> Create roles ([link](https://us-east-1.console.aws.amazon.com/iam#/roles/create))

Sources:
https://stackoverflow.com/a/37947853
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html


When you have your AWS credentials, provide them to your boto3.client()

```
aws_region = "eu-north-1"

aws_creds = dict(
    aws_access_key_id=<YOUR KEY ID>,
    aws_secret_access_key=<YOUR KEY>,
)
s3 = boto3.client("s3", region_name=aws_region, **aws_creds)
```

Note: It's safer to store them as environment variables, and not in the code itself
