### ISSUE TITLE
Exercise 2: permission denied

### ISSUE THREAD

**Issue by fatemetardasti96** [danielbeach/data-engineering-practice#22]
I get error 403 and that I don't have permission when sending a request to the url https://www.ncei.noaa.gov/data/local-climatological-data/access/2021/.
How can I get permission? Has the URL changed?

**Comment by sl2902** [comment]
I can access the link. From your browser, are you able to access the page?

**Comment by danielbeach** [comment]
There is no issues with this link, works fine.
