### ISSUE TITLE
Exercise 2-- No files last modified in 2022

### ISSUE THREAD

**Issue by fabianhogger** [danielbeach/data-engineering-practice#31]
Hey everyone ,I think the page might have changed can't find a file modified in 2022 in the link provided, could you confirm? I assume the web scraping is only supposed to be done in that link I guess I could search all the links, but would that be the objective? 
Thanks !!!

**Comment by jeremyfox36** [comment]
@fabianhogger I can confirm, and I was about to raise the same issue but I decided that the actual data matters less than the exercise of getting a file by filtering the html table, and then finding the records with max HourlyDryBulbTemperature.  I also think building in some error handler for this kind of thing, especially when web scraping, is another more important exercise.

**Comment by danielbeach** [comment]
@fabianhogger thanks for letting me know, I update the README to use a new file.
