### ISSUE TITLE
Exercise 2 - 102 files matching last updated ts of `2022-02-07 14:03`

### ISSUE THREAD

**Issue by aspain** [danielbeach/data-engineering-practice#5]
Instructions: You are looking for the file that was Last Modified on 2022-02-07 14:03, you can't cheat and lookup the file number yourself. 

I am planning on having the code identify the proper file, but even when checking manually, there are 102 files with this same last updated timestamp:
![image](https://user-images.githubusercontent.com/15913202/165993937-0dd5df3f-5a8b-4ff0-8373-d63aa85ad42e.png)

Is this intended as part of the exercise? 

Also would be nice to have some sort of solutions/answers available to check if we completed the exercise properly

**Comment by danielbeach** [comment]
Having multiple files is intended. As in real-world data engineering work, many times the requirements are ambiguous and left up to the discretion of the engineer.

**Comment by aspain** [comment]
Makes sense - thanks for the quick response and for the great examples to practice with
